ALTER TABLE student
MODIFY COLUMN birthday DATE NOT NULL;

ALTER TABLE mark
MODIFY COLUMN student_id BIGINT NOT NULL,
MODIFY COLUMN subject_id BIGINT NOT NULL,
ADD CONSTRAINT check_mark
    CHECK (mark>=1 AND mark<=10);

ALTER TABLE subject
ADD CONSTRAINT check_grade
    CHECK (grade>=1 AND grade<=10);

ALTER TABLE paymentType
MODIFY COLUMN name VARCHAR(45) UNIQUE;


ALTER TABLE payment
MODIFY COLUMN type_id BIGINT NOT NULL,
MODIFY COLUMN amount decimal NOT NULL,
MODIFY COLUMN payment_date TIMESTAMP  NOT NULL;

