ALTER TABLE student ALTER COLUMN birthday DATE NOT NULL;

ALTER TABLE mark ALTER COLUMN student_id BIGINT NOT NULL, ALTER COLUMN subject_id BIGINT NOT NULL, ADD CONSTRAINT check_mark
    CHECK (mark>=1 AND mark<=10);

ALTER TABLE subject ADD CONSTRAINT check_grade CHECK (grade>=1 AND grade<=10);

ALTER TABLE paymentType ALTER COLUMN name VARCHAR(45) UNIQUE;


ALTER TABLE payment ALTER COLUMN type_id BIGINT NOT NULL, ALTER COLUMN amount decimal NOT NULL, ALTER COLUMN payment_date TIMESTAMP  NOT NULL;

